#pragma once
#include "main.h"

void solo_awp();
void left();
void right();
void leftRush();
void betterLeft();
void betterLeft2();
void hoodPush();
void tunePid();
void skills();
void skillsStart();
void rightElim();
void skillsTwo();
void skillsThree();
void skillsFour();
void skillsFive();
void fourteen_awp();